FROM python:3.7-alpine
RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev
WORKDIR /code
ADD requirements.txt /code
RUN pip install -r requirements.txt

ADD dev-key.json /code
ADD *.py /code/
CMD ["python", "spider.py"]
