CREATE TABLE match_details (
    account_level int,
    assists int,
    champion varchar(64),
    damage_dealt int,
    damage_taken int,
    deaths int,
    credits int,
    match_date date,
    self_healing int,
    healing int,
    shielding int,
    loadout_card1 varchar(64),
    loadout_card2 varchar(64),
    loadout_card3 varchar(64),
    loadout_card4 varchar(64),
    loadout_card5 varchar(64),
    loadout_card1_level int,
    loadout_card2_level int,
    loadout_card3_level int,
    loadout_card4_level int,
    loadout_card5_level int,
    item1 varchar(64),
    item2 varchar(64),
    item3 varchar(64),
    item4 varchar(64),
    item1_level int,
    item2_level int,
    item3_level int,
    item4_level int,
    talent varchar(64),
    streak int,
    kills int,
    map varchar(64),
    match_id int NOT NULL,
    match_duration int,
    highest_multi_kill int,
    objective_time int,
    party_id int,
    platform varchar(64),
    region varchar(64),
    team1_score int,
    team2_score int,
    team int,
    win_status varchar(64),
    player_id int,
    player_name varchar(64) NOT NULL,
    master_level int,
    primary key (match_id, player_name)
);
